apiVersion: v1
data:
  APP_NAME: nginx-app
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-09T06:29:54Z"
  name: app-config
  namespace: default
  resourceVersion: "3226"
  uid: a07f3808-1242-4bde-a124-3d95d0b3aec0
